[program:gestion-incidents-ceet-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/gestion-incidents-ceet/current
command=/usr/bin/php artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --no-interaction
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/gestion-incidents-ceet-worker.log
stopwaitsecs=60
